// <auto-generated />
using System;
using InventoryControl.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryControl.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260415025731_AddModuleToPermission")]
    partial class AddModuleToPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryControl.Entity.DO", b =>
                {
                    b.Property<string>("DoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("do_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("DoNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_number");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("ScannerType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scanner_type");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("DoId");

                    b.ToTable("tb_DO");
                });

            modelBuilder.Entity("InventoryControl.Entity.DODetail", b =>
                {
                    b.Property<string>("DoDetailId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("do_detail_id");

                    b.Property<string>("DoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("do_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("itm_id");

                    b.Property<int?>("QtyRequired")
                        .HasColumnType("int")
                        .HasColumnName("qty_required");

                    b.HasKey("DoDetailId");

                    b.HasIndex("DoId");

                    b.HasIndex("ItemId");

                    b.ToTable("tb_DO_Detail");
                });

            modelBuilder.Entity("InventoryControl.Entity.HistoryPrint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("itm_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ref_no");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tag_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trs_type");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TagId");

                    b.ToTable("tb_History_Print");
                });

            modelBuilder.Entity("InventoryControl.Entity.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("ItmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("itm_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("itm_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ItmId")
                        .IsUnique();

                    b.ToTable("tb_Item");
                });

            modelBuilder.Entity("InventoryControl.Entity.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loc_desc");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("LocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loc_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loc_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("tb_Location");
                });

            modelBuilder.Entity("InventoryControl.Entity.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module_key");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module_name");

                    b.HasKey("Id");

                    b.ToTable("tb_Module");
                });

            modelBuilder.Entity("InventoryControl.Entity.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_desc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_name");

                    b.Property<string>("PerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("per_id");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PerId")
                        .IsUnique();

                    b.ToTable("tb_Permission");
                });

            modelBuilder.Entity("InventoryControl.Entity.Reader", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("loc_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rdr_name");

                    b.Property<string>("RdrId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("rdr_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RdrId")
                        .IsUnique();

                    b.ToTable("tb_Reader");
                });

            modelBuilder.Entity("InventoryControl.Entity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_name");

                    b.HasKey("Id");

                    b.ToTable("tb_Role");
                });

            modelBuilder.Entity("InventoryControl.Entity.Role_Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<int?>("Override")
                        .HasColumnType("int")
                        .HasColumnName("is_override");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("permission_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_Role_Permission");
                });

            modelBuilder.Entity("InventoryControl.Entity.StockTaking", b =>
                {
                    b.Property<string>("SttId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("stt_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("SttId");

                    b.ToTable("tb_Stock_Taking");
                });

            modelBuilder.Entity("InventoryControl.Entity.StockTakingDetail", b =>
                {
                    b.Property<string>("StdId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("st_detail_id");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("item_id");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<string>("SttId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("stt_id");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tag_id");

                    b.HasKey("StdId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SttId");

                    b.HasIndex("TagId");

                    b.ToTable("tb_Stock_Taking_Detail");
                });

            modelBuilder.Entity("InventoryControl.Entity.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("EpcTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tag_epc");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("itm_id");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("loc_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("isDelete")
                        .HasColumnType("int")
                        .HasColumnName("isDelete");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.ToTable("tb_Tag");
                });

            modelBuilder.Entity("InventoryControl.Entity.Transaction", b =>
                {
                    b.Property<string>("TrsId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("trs_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("ReaderId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("rdr_id");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reference_id");

                    b.Property<string>("TrsType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trs_type");

                    b.HasKey("TrsId");

                    b.HasIndex("ReaderId");

                    b.ToTable("tb_Transaction");
                });

            modelBuilder.Entity("InventoryControl.Entity.Transaction_Detail", b =>
                {
                    b.Property<string>("TrdId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("trs_detail_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("itm_id");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tag_id");

                    b.Property<string>("TrsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("trs_id");

                    b.HasKey("TrdId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TagId");

                    b.HasIndex("TrsId");

                    b.ToTable("tb_Transaction_Detail");
                });

            modelBuilder.Entity("InventoryControl.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isDelete");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("usr_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_name");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tb_User");
                });

            modelBuilder.Entity("InventoryControl.Entity.User_Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_User_Role");
                });

            modelBuilder.Entity("InventoryControl.Entity.DODetail", b =>
                {
                    b.HasOne("InventoryControl.Entity.DO", "DO")
                        .WithMany("Details")
                        .HasForeignKey("DoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DO");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventoryControl.Entity.HistoryPrint", b =>
                {
                    b.HasOne("InventoryControl.Entity.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InventoryControl.Entity.Permission", b =>
                {
                    b.HasOne("InventoryControl.Entity.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("InventoryControl.Entity.Reader", b =>
                {
                    b.HasOne("InventoryControl.Entity.Location", "LocationNavigation")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationNavigation");
                });

            modelBuilder.Entity("InventoryControl.Entity.Role_Permission", b =>
                {
                    b.HasOne("InventoryControl.Entity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InventoryControl.Entity.StockTakingDetail", b =>
                {
                    b.HasOne("InventoryControl.Entity.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventoryControl.Entity.StockTaking", "StockTaking")
                        .WithMany("Details")
                        .HasForeignKey("SttId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("StockTaking");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InventoryControl.Entity.Tag", b =>
                {
                    b.HasOne("InventoryControl.Entity.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("InventoryControl.Entity.Transaction", b =>
                {
                    b.HasOne("InventoryControl.Entity.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("InventoryControl.Entity.Transaction_Detail", b =>
                {
                    b.HasOne("InventoryControl.Entity.Item", "Item")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Tag", "Tag")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TrsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("InventoryControl.Entity.User_Role", b =>
                {
                    b.HasOne("InventoryControl.Entity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InventoryControl.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryControl.Entity.DO", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("InventoryControl.Entity.Item", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("InventoryControl.Entity.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("InventoryControl.Entity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("InventoryControl.Entity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InventoryControl.Entity.StockTaking", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("InventoryControl.Entity.Tag", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("InventoryControl.Entity.Transaction", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("InventoryControl.Entity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
